# Generated by Django 2.2.7 on 2019-11-18 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='name',
        ),
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
