# Generated by Django 2.2.7 on 2019-11-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommer', '0003_auto_20191118_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='project',
            new_name='user',
        ),
    ]
