# Generated by Django 2.2.7 on 2019-11-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommer', '0004_auto_20191118_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
