# Generated by Django 2.2.7 on 2019-11-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommer', '0005_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=300, null=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommer.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
