# Generated by Django 2.2.7 on 2019-11-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommer', '0006_auto_20191118_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.EmailField(max_length=300, null=True),
        ),
    ]
