# Generated by Django 2.2.7 on 2019-11-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommer', '0013_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created_at', 'permissions': (('hide_post', 'can_add'),)},
        ),
    ]
