# Generated by Django 2.2.7 on 2019-11-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommer', '0014_auto_20191122_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created_at', 'permissions': (('hide_post', 'Can hide post'), ('post_add', 'Can add post'))},
        ),
    ]
